version: '3.8'

services:
  app:
    image: sunil3gs98/dot_application_with_mogodb:latest
    ports:
      - "5035:5035"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/ProductDB
      #- MONGO_CONNECTION_STRING=mongodb://root:example@mongo:27017/ProductDB?authSource=admin
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/ProductDB
      ME_CONFIG_BASICAUTH: false
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
