version: '3.8'

services:
  app:
    image: mb
    ports:
      - "5035:5035"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/ProductDB
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
