apiVersion: v1
kind: Service
metadata:
  name: Dotnet-app-service
  namespace: sunil3gs98
  labels:
    app: Dotnet
spec:
  selector:
    app: Dotnet
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
